config/routes.rb
Rails.application.routes.draw do
  resources :iphones
  devise_for :users
  root 'pages#home'

end

app/models/iphone.rb
class Iphone < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/iphones_controller.rb
class IphonesController < ApplicationController
  before_action :set_iphone, only: [:show, :edit, :update, :destroy]

  respond_to :html

  # GET /iphones
  # GET /iphones.json
  def index
    @iphones = Iphone.all
    respond_with(@iphones)
  end

  # GET /iphones/1
  # GET /iphones/1.json
  def show
    respond_with(@iphones)
  end

  # GET /iphones/new
  def new
    @iphone = Iphone.new
    respond_with(@iphones)
  end

  # GET /iphones/1/edit
  def edit
   respond_with(@iphones)
  end

  # POST /iphones
  # POST /iphones.json
  def create
    @iphone = Iphone.new(iphone_params)
    @iphone.save
    respond_with(@iphones)

    respond_to do |format|
      if @iphone.save
        format.html { redirect_to @iphone, notice: 'Iphone was successfully created.' }
        format.json { render :show, status: :created, location: @iphone }
      else
        format.html { render :new }
        format.json { render json: @iphone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /iphones/1
  # PATCH/PUT /iphones/1.json
  def update
    respond_to do |format|
      if @iphone.update(iphone_params)
        format.html { redirect_to @iphone, notice: 'Iphone was successfully updated.' }
        format.json { render :show, status: :ok, location: @iphone }
      else
        format.html { render :edit }
        format.json { render json: @iphone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /iphones/1
  # DELETE /iphones/1.json
  def destroy
    @iphone.destroy
    respond_to do |format|
      format.html { redirect_to iphones_url, notice: 'Iphone was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_iphone
      @iphone = Iphone.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def iphone_params
      params.require(:iphone).permit(:Model, :Memory, :Condition, :Price, :Availability)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	if current_user
  		redirect_to iphones_path
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/iphones_helper.rb
module IphonesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/iphones/_form.html.erb
<%= simple_form_for(@iphone) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :Model %>
    <%= f.input :Memory %>
    <%= f.input :Condition %>
    <%= f.input :Price %>
    <%= f.input :Availability %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/iphones/edit.html.erb
<h1>Editing Iphone</h1>

<%= render 'form' %>

<%= link_to 'Show', @iphone %> |
<%= link_to 'Back', iphones_path %>

app/views/iphones/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Iphones</h1>

<table>
  <thead>
    <tr>
      <th>Model</th>
      <th>Gbs</th>
      <th>Memory</th>
      <th>Condition</th>
      <th>Price</th>
      <th>Availability</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @iphones.each do |iphone| %>
      <tr>
        <td><%= iphone.Model %></td>
        <td><%= iphone.Memory %></td>
        <td><%= iphone.Condition %></td>
        <td><%= iphone.Price %></td>
        <td><%= iphone.Availability %></td>
        <td><%= link_to 'Show', iphone %></td>
        <td><%= link_to 'Edit', edit_iphone_path(iphone) %></td>
        <td><%= link_to 'Destroy', iphone, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Iphone', new_iphone_path %>

app/views/iphones/new.html.erb
<h1>New Iphone</h1>

<%= render 'form' %>

<%= link_to 'Back', iphones_path %>

app/views/iphones/show.html.erb
<div class= "row">
  <div class= "col-md-6">
    <%= image_tag "iphone5.jpg", class: "img-responsive" %>
    </div>
    <div class= "col-md-6">
      <h3><%= @iphone.Model %> with <%= @iphone.Memory %></h3>
      <p><%= @iphone.Condition %></p>
       <h4 class="text-center"><%= @iphone.Price.to_f %></h4>
    </div>
    </div>

<%= link_to 'Edit', edit_iphone_path(@iphone) %> |
<%= link_to 'Back', iphones_path %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Flip.ie", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      

      <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "iPhones", iphones_path %></li>
      
      <% if current_user %>
      
      <li><%= link_to "Settings", edit_user_registration_path %></li>
      <li><%= link_to "Logout", destroy_user_session_path, method: :delete %>
      
      <% else %>
      
        <li><%= link_to "Login", new_user_session_path %></li>
      
      <% end %>

      <li>

      </li>

      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Estuk</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "layouts/header" %>
<div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/pages/home.html.erb
<div class="jumbotron">
<h1>Welcome to Flip.ie</h1>
<p>The easiest way to buy and sell iPhones</p>
<%= link_to "iPhones", iphones_path, class: "btn btn-primary btn-block" %>
<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-block" %>
</div>